language: generic
include:
- os: linux
addons:
  apt:
    update: true
sudo: required
dist: xenial
git:
  depth: 22
before_script:
- sudo apt-get install devscripts debhelper lxqt-sudo
script:
- chmod +x debuild.sh
- "./debuild.sh |& tee log.txt"
notifications: 
slack: fossasia:3pMkQrSogvEMfnu9aJDW2ZYC
