language: generic
include:
- os: linux
addons:
  apt:
    update: true
sudo: required
dist: xenial
git:
  depth: 22
before_script:
- sudo apt-get install devscripts debhelper lxqt-sudo fakeroot
script:
- chmod +x debuild.sh
- "./debuild.sh |& tee log.txt"
after_script:
 - export lock_package="`echo systemlock_*_all.deb`"
 - cat systemlock_*_all.deb > "/home/travis/${lock_package}"
notifications: 
slack: fossasia:3pMkQrSogvEMfnu9aJDW2ZYC
